spring:
  datasource:
    url: jdbc:mysql://10.20.69.167:3306/content_center
    hikari:
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
        # namespace: 57b954a8-e0ec-4a35-9ddd-2a3d0d6bdec6
        metadata:
          # 自己这个实例的版本
          version: v1
          # 允许调用的提供者版本
          target-version: v1
    sentinel:
      transport:
        dashboard: localhost:8080
  application:
    name: content-center
  main:
    allow-bean-definition-overriding: true
server:
  port: 8010
#user-center:
#  ribbon:
ribbon:
  eager-load:
    enabled: true
    clients: user-center
  #    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
logging:
  level:
    com.itmuch.contentcenter.feignclient.UserCenterFeignClient: debug
feign:
  client:
    config:
      default:
        loggerLevel: full
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
management:
  endpoints:
    web:
      exposure:
        include: '*'